name: ml_ass_1
channels:
  - defaults
dependencies:
  - _py-xgboost-mutex=2.0
  - _tflow_select=2.3.0
  - absl-py=0.15.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=4.0.1
  - attrs=21.2.0
  - backcall=0.2.0
  - blas=1.0
  - blinker=1.4
  - bottleneck=1.3.2
  - brotli=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - ca-certificates=2021.10.26
  - cachetools=4.2.2
  - certifi=2021.10.8
  - cffi=1.15.0
  - charset-normalizer=2.0.4
  - click=8.0.3
  - colorama=0.4.4
  - cryptography=3.4.8
  - cycler=0.11.0
  - dataclasses=0.8
  - decorator=5.1.1
  - fonttools=4.25.0
  - freetype=2.10.4
  - frozenlist=1.2.0
  - gast=0.4.0
  - google-auth=1.33.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - graphviz=2.38
  - grpcio=1.42.0
  - h5py=2.10.0
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - idna=3.3
  - importlib-metadata=4.8.2
  - intel-openmp=2021.4.0
  - ipython=7.31.1
  - jedi=0.18.1
  - joblib=1.1.0
  - jpeg=9d
  - keras=2.4.3
  - keras-applications=1.0.8
  - keras-base=2.4.3
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.1
  - libffi=3.4.2
  - libpng=1.6.37
  - libprotobuf=3.19.1
  - libtiff=4.2.0
  - libwebp=1.2.0
  - libxgboost=1.5.0
  - lz4-c=1.9.3
  - markdown=3.3.4
  - matplotlib=3.5.0
  - matplotlib-base=3.5.0
  - matplotlib-inline=0.1.2
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - multidict=5.1.0
  - munkres=1.1.4
  - numexpr=2.8.1
  - numpy-base=1.21.2
  - oauthlib=3.1.1
  - olefile=0.46
  - openssl=1.1.1m
  - opt_einsum=3.3.0
  - packaging=21.3
  - pandas=1.3.5
  - parso=0.8.3
  - pickleshare=0.7.5
  - pillow=8.4.0
  - pip=21.2.2
  - plotly=5.1.0
  - prompt-toolkit=3.0.20
  - protobuf=3.19.1
  - py-xgboost=1.5.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pydotplus=2.0.2
  - pygments=2.11.2
  - pyjwt=2.1.0
  - pyopenssl=21.0.0
  - pyparsing=3.0.4
  - pyqt=5.9.2
  - pyreadline=2.1
  - pysocks=1.7.1
  - python=3.8.12
  - python-dateutil=2.8.2
  - pytz=2021.3
  - qt=5.9.7
  - requests=2.27.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=1.0.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - setuptools=58.0.4
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.37.0
  - tenacity=8.0.1
  - tensorboard=2.4.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow=2.3.0
  - tensorflow-base=2.3.0
  - tensorflow-estimator=2.6.0
  - termcolor=1.1.0
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - tornado=6.1
  - traitlets=5.1.1
  - typing-extensions=3.10.0.2
  - typing_extensions=3.10.0.2
  - tzdata=2021e
  - urllib3=1.26.7
  - vc=14.2
  - vs2015_runtime=14.27.29016
  - wcwidth=0.2.5
  - werkzeug=2.0.2
  - wheel=0.37.1
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - wrapt=1.13.3
  - xgboost=1.5.0
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.6.3
  - zipp=3.7.0
  - zlib=1.2.11
  - zstd=1.4.9
  - pip:
    - configparser==5.2.0
    - docker-pycreds==0.4.0
    - docopt==0.6.2
    - gitdb==4.0.9
    - gitpython==3.1.26
    - imbalanced-learn==0.9.0
    - numpy==1.19.5
    - pathtools==0.1.2
    - pipreqs==0.4.11
    - promise==2.3
    - psutil==5.9.0
    - pyyaml==6.0
    - sentry-sdk==1.5.3
    - shortuuid==1.0.8
    - smmap==5.0.0
    - subprocess32==3.5.4
    - wandb==0.12.9
    - yarg==0.1.9
    - yaspin==2.1.0
    - yellowbrick==1.3.post1
